# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylegend_display_mk2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DisplayWindow(object):
    def setupUi(self, DisplayWindow):
        DisplayWindow.setObjectName("DisplayWindow")
        DisplayWindow.resize(236, 274)
        self.centralwidget = QtWidgets.QWidget(DisplayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(70, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.color1 = QtWidgets.QLineEdit(self.centralwidget)
        self.color1.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.color1.setObjectName("color1")
        self.color2 = QtWidgets.QLineEdit(self.centralwidget)
        self.color2.setGeometry(QtCore.QRect(20, 60, 41, 21))
        self.color2.setObjectName("color2")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(70, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.color3 = QtWidgets.QLineEdit(self.centralwidget)
        self.color3.setGeometry(QtCore.QRect(20, 100, 41, 21))
        self.color3.setObjectName("color3")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(70, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.color4 = QtWidgets.QLineEdit(self.centralwidget)
        self.color4.setGeometry(QtCore.QRect(20, 140, 41, 21))
        self.color4.setObjectName("color4")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(70, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(70, 220, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.color5 = QtWidgets.QLineEdit(self.centralwidget)
        self.color5.setGeometry(QtCore.QRect(20, 180, 41, 21))
        self.color5.setObjectName("color5")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(70, 180, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.color6 = QtWidgets.QLineEdit(self.centralwidget)
        self.color6.setGeometry(QtCore.QRect(20, 220, 41, 21))
        self.color6.setObjectName("color6")
        DisplayWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DisplayWindow)
        self.statusbar.setObjectName("statusbar")
        DisplayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DisplayWindow)
        QtCore.QMetaObject.connectSlotsByName(DisplayWindow)

    def retranslateUi(self, DisplayWindow):
        _translate = QtCore.QCoreApplication.translate
        DisplayWindow.setWindowTitle(_translate("DisplayWindow", "PyLegend Display"))
        self.label1.setText(_translate("DisplayWindow", "LegendDisplay"))
        self.label2.setText(_translate("DisplayWindow", "LegendDisplay"))
        self.label3.setText(_translate("DisplayWindow", "LegendDisplay"))
        self.label4.setText(_translate("DisplayWindow", "LegendDisplay"))
        self.label5.setText(_translate("DisplayWindow", "LegendDisplay"))
        self.label6.setText(_translate("DisplayWindow", "LegendDisplay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DisplayWindow = QtWidgets.QMainWindow()
    ui = Ui_DisplayWindow()
    ui.setupUi(DisplayWindow)
    DisplayWindow.show()
    sys.exit(app.exec_())
