# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylegend_configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWindow(object):
    def setupUi(self, ConfigWindow):
        ConfigWindow.setObjectName("ConfigWindow")
        ConfigWindow.resize(425, 239)
        self.centralwidget = QtWidgets.QWidget(ConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.darkmodebox = QtWidgets.QCheckBox(self.centralwidget)
        self.darkmodebox.setGeometry(QtCore.QRect(10, 20, 151, 23))
        self.darkmodebox.setObjectName("darkmodebox")
        self.confipathedit = QtWidgets.QLineEdit(self.centralwidget)
        self.confipathedit.setGeometry(QtCore.QRect(150, 90, 251, 25))
        self.confipathedit.setObjectName("confipathedit")
        self.fontsizeabel = QtWidgets.QLabel(self.centralwidget)
        self.fontsizeabel.setGeometry(QtCore.QRect(250, 20, 67, 21))
        self.fontsizeabel.setObjectName("fontsizeabel")
        self.fontlabel = QtWidgets.QLabel(self.centralwidget)
        self.fontlabel.setGeometry(QtCore.QRect(250, 50, 67, 21))
        self.fontlabel.setObjectName("fontlabel")
        self.fontbox = QtWidgets.QComboBox(self.centralwidget)
        self.fontbox.setGeometry(QtCore.QRect(310, 50, 86, 25))
        self.fontbox.setObjectName("fontbox")
        self.fontsizebox = QtWidgets.QSpinBox(self.centralwidget)
        self.fontsizebox.setGeometry(QtCore.QRect(350, 20, 44, 26))
        self.fontsizebox.setObjectName("fontsizebox")
        self.applybutton = QtWidgets.QPushButton(self.centralwidget)
        self.applybutton.setGeometry(QtCore.QRect(170, 180, 89, 25))
        self.applybutton.setObjectName("applybutton")
        self.confidirlabel = QtWidgets.QLabel(self.centralwidget)
        self.confidirlabel.setGeometry(QtCore.QRect(20, 90, 121, 21))
        self.confidirlabel.setObjectName("confidirlabel")
        self.configfilelabel = QtWidgets.QLabel(self.centralwidget)
        self.configfilelabel.setGeometry(QtCore.QRect(20, 130, 111, 21))
        self.configfilelabel.setObjectName("configfilelabel")
        self.configfileedit = QtWidgets.QLineEdit(self.centralwidget)
        self.configfileedit.setGeometry(QtCore.QRect(150, 130, 251, 25))
        self.configfileedit.setObjectName("configfileedit")
        self.applyclosebutton = QtWidgets.QPushButton(self.centralwidget)
        self.applyclosebutton.setGeometry(QtCore.QRect(310, 180, 89, 25))
        self.applyclosebutton.setObjectName("applyclosebutton")
        ConfigWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConfigWindow)
        self.statusbar.setObjectName("statusbar")
        ConfigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigWindow)

    def retranslateUi(self, ConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigWindow.setWindowTitle(_translate("ConfigWindow", "Config Menu"))
        self.darkmodebox.setText(_translate("ConfigWindow", "Darkmode"))
        self.fontsizeabel.setText(_translate("ConfigWindow", "Fontsize"))
        self.fontlabel.setText(_translate("ConfigWindow", "Font"))
        self.applybutton.setText(_translate("ConfigWindow", "Apply"))
        self.confidirlabel.setText(_translate("ConfigWindow", "Config Directory"))
        self.configfilelabel.setText(_translate("ConfigWindow", "Default Config"))
        self.applyclosebutton.setText(_translate("ConfigWindow", "Apply & Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigWindow = QtWidgets.QMainWindow()
    ui = Ui_ConfigWindow()
    ui.setupUi(ConfigWindow)
    ConfigWindow.show()
    sys.exit(app.exec_())
